version: "3.8"

services:
  app:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - ./:/app
    command: bun run dev
    ports:
      - "3000:3000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_KEY=${FIREBASE_SERVICE_ACCOUNT_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - PORT=3000
      # Uncomment below to use emulator in your code
      # - FIRESTORE_EMULATOR_HOST=firestore:8080
    depends_on:
      - firestore

  firestore:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_PROJECT_ID=skillsphere-yuvaai
